### PR TITLE
Replace gulp notify

### LINKED ISSUE #305: gulp-notify hangs
## Describe the bug
When compiling, the process will hang at the end sometimes based on current notification settings.

## To Reproduce
Cut off notifications (focus assist), run `gulp`.

## Expected behavior
Fully run the gulp process without hanging, no matter notification settings.

### PR DESCRIPTION
**Pull request by tksheppard**
## Related to Issue
Fixes #305 

## Description
I replaced `gulp-notify` with `fancy-log`. This simpler solution doesn't interact with windows notifications, which resolves problems created by such. Instead of showing every file being distributed, it shows how many files for batch jobs. For single resolution jobs, it shows confirmation that it has been completed as expected.

## How Has This Been Tested?
I have ran both `gulp` and `gulp package` successfully and without it hanging. The logs are clear and work correctly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -299,26 +347,22 @@ function zipdist() {
...
   return gulp.src(paths.zipcontainers.src)
     .pipe(zip(paths.zipcontainers.zipfile))
     .pipe(gulp.dest(paths.zipcontainers.dest))
-    .pipe(notify({message: '<%= file.relative %> temporarily created!', title : 'zipcontainers'}));
 }
 
 // ZIP everything else
 function zipelse() {
   return gulp.src(paths.zipelse.src, {base: '.'})
     .pipe(gulp.dest(paths.zipelse.dest))
```
Comment (david-poindexter) [inline gulpfile.js:362]:
```suggestion
    .pipe(gulp.dest(paths.zipelse.dest))
    .on('end', function() {
      log('zipelse temporarily created!');
    })
```

File: gulpfile.js [hunk 2]
```diff
@@ -299,26 +347,22 @@ function zipdist() {
...
-    .pipe(notify({message: '<%= file.relative %> temporarily created!', title : 'zipcontainers'}))
     .pipe(replace('dist/', ''))
     .pipe(zip(paths.zipelse.zipfile))
     .pipe(gulp.dest(paths.zipelse.dest))
```
Comment (david-poindexter) [inline gulpfile.js:365]:
```suggestion
    .pipe(gulp.dest(paths.zipelse.dest))
    .on('end', function() {
      log('dist path removed and zipdist temporarily recreated!');
    })
```

**Review by david-poindexter — APPROVED** [review]
Thanks @tksheppard 🎉  I am just going to make a few small modifications to help with the log messages.
